### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by rahulbamnuya**
Issue : #121 
After chatbot addition :
WhatsApp Image 2024-10-28 at 11 33 01 PM

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@rahulbamnuya add a video showcasing how the chatbot works, and also fix its location why is it showing above the navbar. plz put it in a suitable location. make sure your PR is using the latest version of the project. complete these steps asap so i can merge your pr in time so that you get points for gssoc.

**Comment by zoobiasyed** [comment]
@rahulbamnuya kindly upload the video of how your chatbot is working, and make necessary adjustments in your code to properly locate the chatbot on the screen. As already mentioned by Amna do it asap so that she can merge your pr.

**Comment by zoobiasyed** [comment]
@rahulbamnuya kindly update us on the status of chatbot's location and it's working video.

**Comment by zoobiasyed** [comment]
@rahulbamnuya you haven't updated us on the chatbot's location and working video. If you want your work to be merged kindly do it asap.

**Comment by zoobiasyed** [comment]
@rahulbamnuya your pr will only be merged if all the relevant details and pictures are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
No Reply from weeks so im closing this pr.

**Pull request closed without merging**
