### PR TITLE
updting top button  bug

### PR DESCRIPTION
**Pull request by Harshitraaaj**
Checking bug and i didnt find any issue , so simply update few indentations. #94 fixed.

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@Harshitraaaj attach the relevant screenshot PR should pass the required tests.

**Comment by Harshitraaaj** [comment]
Here is the video_link : https://drive.google.com/file/d/1yQqckRsYTFqeE9g7KKpmXkgMDvB_2kMV/view?usp=drivesdk

**Comment by Harshitraaaj** [comment]
@Amna-Hassan04 whats the update , Merge this pull req. , it will give me points for gssoc

**Review by Amna-Hassan04 — APPROVED** [review]
their was a indentation issue. which seems to be fixed. good to be merged.

**Pull request merged**
