### PR TITLE
[FEATURE] - Daily Affirmations Widget

### LINKED ISSUE #154: [FEATURE] - Daily Affirmations Widget
### Feature Title

Daily Affirmations Widget

### **Daily Affirmations Widget**

Users of the SereniFi app seek effective ways to enhance their mental well-being and maintain a positive mindset. However, many users may find it challenging to engage consistently with the app without regular prompts or reminders. The absence of a feature that delivers daily motivational content limits users' opportunities for positive reinforcement and may hinder their journey toward mental tranquility. 

To address this issue, the Daily Affirmations Widget will provide users with fresh, uplifting affirmations every day, encouraging them to engage with the app regularly. This feature aims to foster a habit of positivity and mindfulness, ultimately contributing to improved emotional resilience and overall well-being.

### Proposed Solution

**Summary**:  
We propose the addition of a **Daily Affirmations Widget** to the SereniFi app. This feature aims to enhance user engagement and promote mental well-being through positive reinforcement.

---

**Description**:  
The Daily Affirmations Widget will display a new positive affirmation daily or at a user-defined interval. Users can choose from different themes such as confidence, relaxation, and productivity. The widget will refresh automatically and allow users to receive push notifications for daily affirmations.

---

**Benefits**:
- **Encourages Consistency**: Regular interaction with the widget will help keep users engaged with the app daily.
- **Boosts Mental Well-being**: Positive affirmations can improve users' emotional resilience and motivation, enhancing their overall experience with the app.
- **User Retention**: By providing valuable content that users can incorporate into their daily routine, we can increase the likelihood of users continuing to use the app.

---

**Acceptance Criteria**:
1. Users should see a new affirmation each day or upon refreshing the widget.
2. Users can select themes for their affirmations (e.g., confidence, relaxation).
3. Users should have the option to enable push notifications for daily affirmations.
4. Affirmations should be stored in the database and can be personalized based on user preferences.
5. The widget should be visually appealing and user-friendly, integrating seamlessly into the existing UI.

---

### **Tech Stack Suggestions for Web**:
- **Frontend**: 
  - **React**: For building the user interface and managing component states.
  - **CSS/SCSS**: For styling the widget and ensuring a visually appealing design.

- **Backend**: 
  - **Node.js** with **Express**: To create a RESTful API for managing user preferences and delivering affirmations.

- **Database**: 
  - **Firebase Firestore** or **MongoDB**: For storing user data, affirmation preferences, and managing daily content.

- **Push Notifications**: 
  - **Firebase Cloud Messaging (FCM)**: For sending daily affirmation notifications to users.

- **Scheduling/Automation**: 
  - **Node.js Cron Jobs** or **Firebase Cloud Functions**: For automating the daily refresh of affirmations.

---

> **Please assign this issue to me, I'll be more than happy to work on such a mindful project.**

### Alternatives Considered

N/A

### Additional Context

This feature aligns perfectly with SereniFi’s mission to help users achieve mental tranquility and enhance their well-being, providing both immediate and long-term benefits.

### PR DESCRIPTION
**Pull request by sanchitc05**
Fixes #154

# Daily Affirmations Widget Implementation

## Overview
This PR introduces a new Daily Affirmations Widget to enhance user well-being through regular positive affirmations. The widget provides personalized, theme-based affirmations that automatically refresh at user-defined intervals.

### Core Functionality
- **Theme-Based Affirmations**: 
  - Confidence boosters
  - Relaxation prompts
  - Productivity enhancers
  - Easily extensible for additional themes

- **Dynamic Refresh System**:
  - Configurable refresh intervals (1-60 minutes)
  - Automatic updates based on user preferences
  - Manual refresh option
  - Last update timestamp display

- **User Preferences**:
  - Theme selection
  - Refresh interval customization
  - Push notification toggle
  - Preference persistence

### Technical Implementation
- **State Management**:
  - Utilizes Streamlit's session state for persistence
  - Efficient affirmation caching
  - Timestamp tracking for updates

- **UI/UX Enhancements**:
  - Custom CSS styling
  - Responsive design
  - Intuitive controls
  - Clear visual hierarchy

## Code Changes
- Added `AffirmationWidget` class
- Implemented theme-based affirmation storage
- Created display logic with Streamlit components
- Added custom styling and layout improvements
- Integrated session state management
- Implemented refresh mechanism

## Dependencies
Added to requirements.txt:
```txt
streamlit>=1.28.0
python-dateutil>=2.8.2
pytz>=2023.3

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@sanchitc05 Add all the relevant screenshots / video recordings showcasing your work.

**Comment by sanchitc05** [comment]
@Amna-Hassan04 here are the screenshots for your reference

**Comment by sanchitc05** [comment]
@Amna-Hassan04 here are the screenshots for your reference

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly look at all the relevant pictures, if you feel everything is in place. Kindly merge it.

**Comment by sanchitc05** [comment]
@Amna-Hassan04 please check the pr and merge it if everything feels right.

**Comment by sanchitc05** [comment]
@Amna-Hassan04 can you please give level 3 or at least level 3 label, it would really appreciate my efforts.
Thank you!

**Comment by sanchitc05** [comment]
@MastanSayyad @sanjay-kv can you please give me at least level 2 label for this pr.

**Comment by Amna-Hassan04** [comment]
@sanchitc05 A level2 or level3 requires that u must have implemented some new feature or solved an important or complex issue. since your PR does none of that I have labeled it a level1. The functionality is even already implemented in the tips section that u have reorganized it into a new heading.

**Pull request merged**
