### PR TITLE
Blue Link Visibility Issue Solved

### LINKED ISSUE #112: [BUG] - Blue Link Visibility Issue
### Bug Title

Blue Links Visibility Issue 

### Description

There is a visibility issue with blue-colored links on the game page due to a background color change to blue, making the links difficult to see.

### Steps to Reproduce

1. Go to the website.
3. Click on the "Game" button.
4. Observe that the links are displayed in blue, making them blend with the background.

### Expected Behavior

The links should either be placed inside a button or displayed in a different color to ensure they are visible and distinguishable from the background.

### Environment

Operating System: Windows (All Versions) , Browsers: Chrome, Edge

### Additional Context

https://github.com/user-attachments/assets/d4bb8316-4f10-489b-9cca-6583daf54c17

@Amna-Hassan04

### PR DESCRIPTION
**Pull request by Rahul-AkaVector**
### Pull Request Title:
**✨ Blue Link Visibility Issue Solved✨**

#### Summary
This pull request addresses the visibility issue of blue links on the game page and includes additional enhancements to the layout of mini-games. 🎮

#### Related Issue:
Fixes #112 - Blue Links Visibility Issue 🔧

#### Changes Made:
- **🔵 Visibility Fix**: Adjusted the style of blue links to ensure they are distinguishable from the background color on the game page.
- **🗂️ Game Layout**: Implemented a tabular format for the mini-games section, allowing for better organization and accessibility.
- **🎉 Added Games**: Expanded the selection of fun mini-games from 3 to 12, making it easier for users to choose a game.
- **🌟 Improved Design**: Ensured that the overall aesthetic and usability of the game page are enhanced with the new layout.
- **🔗 Game Links**: All game links are working and properly redirect to their respective sites.

#### Screenshots/Videos:
[Screenshot Description](https://github.com/user-attachments/assets/cb25e2b2-50f4-44e7-9e16-8c9fcc7273f3)

#### Request for Review:

I believe these changes significantly improve the user experience. Additionally, I found some extra opportunities for enhancement, such as further adjustments to the layout and design elements. I would appreciate it if you could consider adding labels like ```GSSOC``` and ```Hacktoberfest``` to highlight these contributions and prioritize them under a ```Level 2```  label. 🙏

### CODE REVIEW

**Comment by Rahul-AkaVector** [comment]
@Amna-Hassan04 can u Please check the PR and Let me know changes if any

**Comment by Amna-Hassan04** [comment]
@Rahul-AkaVector plz make sure u are using teh latest version of teh project so i can merge this.

**Comment by Rahul-AkaVector** [comment]
@Amna-Hassan04 issues resolved

**Review by Amna-Hassan04 — APPROVED** [review]
looks good to be merged.

**Pull request merged**
