### PR TITLE
Navbar enhanced with same color scheme

### PR DESCRIPTION
**Pull request by Saaarthak0102**
# Enhanced the navbar with better design!
## Fixes Issue #148 
image

### CODE REVIEW

**Comment by Saaarthak0102** [comment]
please review and merge! @Amna-Hassan04

**Review by Saaarthak0102 — COMMENTED** [review]
reviewed

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 merge it as it's completed, do check it before merging.

**Comment by Saaarthak0102** [comment]
please merge @Amna-Hassan04

**Comment by Saaarthak0102** [comment]
please merge @Amna-Hassan04

**Comment by Saaarthak0102** [comment]
Hey! Its been a week.
Please review and merge @Amna-Hassan04

**Review by Amna-Hassan04 — COMMENTED** [review]
I want the navbar to be improved but not lose its original style that looks good. This looks very bland, if u want this to be merged you have make the navbar look like the previous one just improve it in some way which would be  better.

**Comment by Saaarthak0102** [comment]
> I want the navbar to be improved but not lose its original style that looks good. This looks very bland, if u want this to be merged you have make the navbar look like the previous one just improve it in some way which would be  better. 

Oh... I thought this one is better and I guess there's no way we can improvise the real one. Thank you for letting me try! 😊

**Comment by zoobiasyed** [comment]
@Saaarthak0102 thank you for your hard work and the improvised version, but as mentioned my Amna kindly make the original one better so she can merge it asap.

**Comment by aslams2020** [comment]
@Amna-Hassan04 
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1369

 **Don't add labels to it now.** 

@Saaarthak0102  You'll get the points in the leaderboard update.

**Comment by aslams2020** [comment]
You can close this PR

**Pull request closed without merging**
