### PR TITLE
Updated README.md, solved Issue 82

### PR DESCRIPTION
**Pull request by sindhuja184**
Solved #82, pip install gave some error in my computer changing it to pip install streamlit lead to the correct functioning of the project. 

Thanks @Amna-Hassan04

### CODE REVIEW

**Review by Amna-Hassan04 — COMMENTED** [review]
you have to add all the required libraries in the statement not just streamlit

**Comment by sindhuja184** [comment]
image
@Amna-Hassan04 added!

**Comment by Amna-Hassan04** [comment]
@sindhuja184 rigth, plz make sure first that you are using the latest version of the project so that i can merge.

**Comment by sindhuja184** [comment]
@Amna-Hassan04, done!

**Pull request merged**
