### PR TITLE
In the Read Me File: Fixed the wrong link in Contributer Table and changed the table style

### LINKED ISSUE #13: In the Read Me File: Fix the wrong link in Contributer Table and change the table to look like the attached sample.
1. Change the table to look like this. 
image

2. In the last 2 contributers images the links are swapped by mistake, assign the pic to the correct profile.

### PR DESCRIPTION
**Pull request by Ayush07571**
Fixes #13 

I swapped  the profile images of lastby mistake, assign the pic to the correct profile. And I also customized the contributor table by linking the github profile of users with their profile pic.

I have attached the screenshots of my work for your reference.

Screenshot 2024-10-02 113944
Screenshot 2024-10-02 113930

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
hey, plz recheck the link to the github profiles. for the 2nd to last contributers why is it dhowing username2, username3, username4.

**Comment by Ayush07571** [comment]
Actually the links were copied from the repository you provided and if we
open the link attached with every profile pic from the old repo the same
link opens.


I have attached some screenshots for your reference

**Comment by Ayush07571** [comment]
if you provide me with the link or github id then I can do that also.

**Comment by Ayush07571** [comment]
Just check once again I have made the changes suggested by you and added the links to the profile by replacing links of username2, username3 and username4.

**Comment by Ayush07571** [comment]
I have attached the screenshots of latest updates, for your reference

Screenshot 2024-10-02 193143
Screenshot 2024-10-02 193133

**Comment by Amna-Hassan04** [comment]
@Ayush07571 mention the issue this resolves, so I can merge this

**Comment by Ayush07571** [comment]
issue number #13

**Comment by Amna-Hassan04** [comment]
@Ayush07571 please link the issue that closes with this pr, dont just write the issue number

**Comment by Ayush07571** [comment]
Fixes #13 

I’ve linked the issue in the PR description as well as in this comment. This should now close issue #13 when the PR is merged. Thank you!

**Review by Amna-Hassan04 — APPROVED** [review]
The table is removed how I requested but the images are not in circular shape, still works for now, merging this because both contributers werent able to shape the images as circular.

**Pull request merged**
