### PR TITLE
Added detailed instruction for Guided breathing

### PR DESCRIPTION
**Pull request by shrehs**
Closes: #199 
Added detailed instruction for guided breathing

Screenshot (142)
Screenshot (143)

Working video:
[Guided_breathing.webm](https://github.com/user-attachments/assets/94d1113b-34d1-4140-a20f-3ead3659e5f2)

### CODE REVIEW

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly look into this, @shrehs has provided us with necessary pictures and a working video. If you feel like it’s complete, merge it asap.

**Comment by shrehs** [comment]
@zoobiasyed and @Amna-Hassan04 #199 issue hasn't been assigned labels yet, could you please look into it

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly add labels to issue #199.

**Review by Amna-Hassan04 — COMMENTED** [review]
The box breathing exercise instructions are not clear, their are only cycles written here liek in our app we have a bar that monitors time for meditation. If u want to add proper instructions this falls short, plus according to the screenshot this doesnt look integrated with the app.py of this app, rather it is just a sample streamlit app.

**Comment by shrehs** [comment]
Hey!
Cool. Will add longer instructions. If you could provide an example on what you are looking I would be glad to work on it also I wanted to ask on integrated part. I have added the code as part of app.py, you can check this in file changed in the PR raised. could help me understand if I have to integrate it somewhere else...
Thank you

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 can you provide @shrehs with a sample writing? That would make her task easier and it would be in accordance with our requirements.

**Comment by zoobiasyed** [comment]
@shrehs your pr will only be merged if all the relevant details and pictures are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
@shrehs I myself dont know about box breathing this was a task that u wanted to work on, but this implementation isnt really helping the user, bcz If i were to follow this I wouldnt be able to. the aesthetic doesnot match teh projects appeal if i were u i would just find a video online and embed it like the one on teh first page of the, if u want to make any changes do it before 7 pm after that the gssoc leaderboard will close, Thanks.

**Comment by Amna-Hassan04** [comment]
@shrehs for now Im closing this pr as this is not relevant if u implement the above points plz raise a pr again before 7 pm, I will review it and merge it if applicable.

**Pull request closed without merging**
