### PR TITLE
This pull request introduces a new feature that allows users to set the duration for meditation in seconds. The application now prompts users to input their desired meditation duration, which is then displayed in the app.

### PR DESCRIPTION
**Pull request by imDarshanGK**
#177 
## Changes Made
- Added a slider input for setting the meditation duration.
- Updated the UI to display the selected duration.
- Initialized the session state for the meditation duration to ensure it functions correctly.

## How to Test
1. Run the application using `streamlit run serenifi_app.py`.
2. Use the slider to set a meditation duration.
3. Verify that the duration is displayed correctly on the screen.

## Future Improvements
- Consider adding validation to ensure the duration is within a reasonable range.
- Explore the option to save user preferences for future sessions.

Please review the changes and let me know if any adjustments are needed!
@Amna-Hassan04

### CODE REVIEW

**Comment by imDarshanGK** [comment]
Hi @Amna-Hassan04 ,

I have completed the integration of voice commands for the meditation feature as assigned. The implementation allows users to set a meditation duration through the Streamlit app, and upon starting the meditation session, it provides voice feedback on the duration.

Please let me know if you have any feedback or if there are additional features you would like me to implement.

Thank you!
@imDarshanGK

**Comment by Amna-Hassan04** [comment]
@imDarshanGK Add all the relevant screenshot / video showcasing your work.

**Review by zoobiasyed — COMMENTED** [review]
Thank you @imDarshanGK for setting the new feature, but for convenience kindly add the relevant pictures and videos on the working of the duration of mediation.

**Comment by imDarshanGK** [comment]
Screenshot_9-11-2024_023_localhost
Screenshot_9-11-2024_0110_localhost

@zoobiasyed

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 look at the provided images, it looks all the requirements are fulfilled and if you feel the same way merge this pr asap.

**Comment by imDarshanGK** [comment]
yes @zoobiasyed

**Review by Amna-Hassan04 — COMMENTED** [review]
firstly this code is not integrated with the app, u have just made a simple steramlit paeg and written yoru code on it, u havent even edited anything with the original apps code. and someone else has already implemented this feature in which time is being tracked for the meditation and a bar is showing it 
image

**Pull request closed without merging**
