### PR TITLE
Github Issue Template 

### PR DESCRIPTION
**Pull request by yasheela-alla**
solves #37

### CODE REVIEW

**Comment by yasheela-alla** [comment]
hey @Amna-Hassan04 please check!

**Comment by Amna-Hassan04** [comment]
@yasheela-alla please do attach a screenshot of how it look like for both options feature request and issues

**Comment by yasheela-alla** [comment]
bug_report: 
image

feature_request:
image

**Comment by yasheela-alla** [comment]
@Amna-Hassan04 Please review and merge if everything looks good!!

**Review by Amna-Hassan04 — APPROVED** [review]
Good to be merged

**Pull request merged**
