### PR TITLE
Enhance Image Display with API Integration #63

### PR DESCRIPTION
**Pull request by Baig-fatema**
#### Overview
This pull request addresses issue #63, which aims to enhance the image display functionality on the SeriniFi website by integrating an external image API. The changes made in this PR improve the user experience by providing a more dynamic and visually appealing presentation of images related to anxiety relief.

#### Changes Made
- **API Integration**: Implemented a connection to [API Name], allowing for the retrieval of high-quality images relevant to the content on the website.
- **Dynamic Image Loading**: Images are now fetched dynamically, ensuring that users see fresh and diverse content each time they visit the site.
- **Responsive Design**: Adjusted the layout to ensure that images are displayed correctly across various screen sizes, enhancing accessibility for all users.
- **Error Handling**: Added error handling to manage API failures gracefully, providing fallback content when necessary.

#### Benefits
- **Improved User Engagement**: By offering a wider variety of images, users are more likely to engage with the content, making their experience more enriching.
- **Enhanced Aesthetic Appeal**: The integration adds a modern touch to the site, making it visually attractive and in line with current design trends.
- **Support for Future Expansion**: This implementation lays the groundwork for further enhancements, such as user-uploaded images or additional image sources.

#### Testing
- Thoroughly tested the image loading functionality across different devices and browsers to ensure compatibility and responsiveness.
- Verified that fallback mechanisms work correctly in cases where the API fails to respond.

#### Next Steps
- Review and feedback are welcome! Any suggestions for improvement or additional features are appreciated as we strive to make SeriniFi the best resource for anxiety relief.

Thank you! @Amna-Hassan04 for considering this enhancement!

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@Baig-fatema Please attach a screen recording of the working feature

**Comment by Baig-fatema** [comment]
@Amna-Hassan04 this is the link to screen recording features of the #63  issue. [https://drive.google.com/file/d/132RnjYjTDJzTAdpXcVPJtv3-KyOmHArW/view?usp=sharing](url)

- i am requesting that please review and merge this.
- this images are responsive and dynamic.
- copy the above link and paste in chrome browser so that you can review it.

**Comment by Baig-fatema** [comment]
(https://drive.google.com/file/d/132RnjYjTDJzTAdpXcVPJtv3-KyOmHArW/view?usp=sharing)

**Comment by Baig-fatema** [comment]
@Amna-Hassan04 this is the link to screen recording features of the #63.

video link:  [https://drive.google.com/file/d/132RnjYjTDJzTAdpXcVPJtv3-KyOmHArW/view](https://drive.google.com/file/d/132RnjYjTDJzTAdpXcVPJtv3-KyOmHArW/view)

- i am requesting that please review and merge this.
- this images are responsive and dynamic.
- copy the above link and paste in chrome browser so that you can review it.

**Comment by Baig-fatema** [comment]
@Amna-Hassan04  also i am requesting that please add the gssoc label and add my points in leader board.

**Comment by Baig-fatema** [comment]
@Amna-Hassan04  and @dev-shinde  i am requesting please review it. and please merge if possible and add my points in leader board.

**Comment by Amna-Hassan04** [comment]
@Baig-fatema it shows this 
image

**Comment by dev-shinde** [comment]
@Baig-fatema give the video view access to all ; so that we can review it

**Comment by Baig-fatema** [comment]
@Amna-Hassan04 and @dev-shinde Sorry for inconvineince.
The video Link : [https://drive.google.com/file/d/132RnjYjTDJzTAdpXcVPJtv3-KyOmHArW/view?usp=sharing](https://drive.google.com/file/d/132RnjYjTDJzTAdpXcVPJtv3-KyOmHArW/view?usp=sharing)

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
The problem is that I dont think the images in this api are visually appealing, since the image rigth now on our home page is very cozy it relaxes u but the images in the implemented api are very dull, more anxeity triggering, so as this is a app whose focus is to have mental wellness this should be made better.

**Comment by zoobiasyed** [comment]
@Baig-fatema your pr will only be merged if all the relevant details and pictures/videos are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
No Reply from more than 10 days hence closing pr.

**Pull request closed without merging**
