### PR TITLE
First Commit(Animations added)

### PR DESCRIPTION
**Pull request by Coder-mania**
**Hello there!** @Amna-Hassan04 
-> Done with the adding of animations.
-> Also a transition to button.

Below are the screenshots/video :
pic 1
pic 2
pic 3
pic 4
pic 5
pic 6

### CODE REVIEW

**Comment by Coder-mania** [comment]
@Amna-Hassan04 
Do lookout on above commit and kindly add the tags 'gssoc-ext2024', 'hactoberfest', and appropriate 'level'.

**Comment by Coder-mania** [comment]
@Amna-Hassan04 can you look into the PR and Merge it.

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
you havent added a video that would show if the animations happen for a second or so and disappear or not. plus according to the screenshots the animations look unnecessary if the the images are just going to stay. I dont know really how they will look in the app unless you link a video showcasing them.   and didnt I ask u to show me a sample of how the animations would look before making a PR?

**Comment by Coder-mania** [comment]
> you havent added a video that would show if the animations happen for a second or so and disappear or not. plus according to the screenshots the animations look unnecessary if the the images are just going to stay. I dont know really how they will look in the app unless you link a video showcasing them. and didnt I ask u to show me a sample of how the animations would look before making a PR?

Added the vedio

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
The Animated emojis are too big. they should be either alligned inside the button or next to it in the same size as the button so they look good. your pr should disturb the overall aesthetic of the app

**Comment by Amna-Hassan04** [comment]
@Coder-mania plz make the proposed changes so i might be able to merge this before gssoc ends.

**Comment by zoobiasyed** [comment]
@Coder-mania have you made the necessary changes that Amna suggested? If not than do it asap so that she can merge it before this ends. Make sure it passes all the tests.

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly look into this.

**Comment by Amna-Hassan04** [comment]
@Coder-mania no screenshot attached for the updated code

**Comment by Amna-Hassan04** [comment]
No reply from all most 2 weeks, closing this pr, if the changes are made plz make a new pr.

**Pull request closed without merging**
