### PR TITLE
FIx Issue #95 : Improvement in Get tips section ( placed in appropriate position)

### PR DESCRIPTION
**Pull request by omkarmakar**
- [X] Tip Should show next to GIF

- [X] Distributed in 2 columns

- [x] Center aligned 

https://github.com/user-attachments/assets/c3e2314b-059b-4389-8d05-f551ca766398

### CODE REVIEW

**Comment by omkarmakar** [comment]
please put labels of hacktoberfest and gssoc extended

**Comment by Amna-Hassan04** [comment]
@omkarmakar plz mention the issue this PR closes.

**Comment by omkarmakar** [comment]
> @omkarmakar plz mention the issue this PR closes.

Did you mean the mentioning the PR id?

**Comment by Amna-Hassan04** [comment]
@omkarmakar the tip has to be shown inside the black background next to the gif, not outside it. and only keep the tip inside the black background next to the gif but this heading has to be above both of them outside the background as it was before. Thanks. 
image

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
the implementation was supposed to be putting tha tips and button inside the gif container on the left to it inside the black background, and the heading should be above outside it. The problem is this does not look visually appealing.

**Comment by Amna-Hassan04** [comment]
@omkarmakar I just checked the original build this is supposed to have white background not black like it is in the original build. put one sample tip next to the gif inside teh container and place the button under it, then when u click teh button a new tip appears. 
image

**Comment by omkarmakar** [comment]
> @omkarmakar I just checked the original build this is supposed to have white background not black like it is in the original build. put one sample tip next to the gif inside teh container and place the button under it, then when u click teh button a new tip appears. image

its not actually about black and white, its about the system settings, mine one is darked theme so its showing dark to me, yours shall be white

image

i just adjusted the settings of the steamlit, now it is white ... but the main issue is the lottie animation json file you have used is taking up full width of the screen, so i decided to break it into 2 columns to get the tips button by the side of the animation, again now the challenge is that i wont get that system settings based background color, but lemme check

From here i explored two option, one is a blank animation of lottie... but its stupid, our tip button cant be placed if added, and next is search for some background which will have no background... technically whatever the system setting is there, it should be the background...

Do you get this? @Amna-Hassan04 ... Share if you have any plans or consider changing the animation or the plan

till then im brainstorming something out, I may tweak with the assets of the animations :)

**Comment by omkarmakar** [comment]
image

**Comment by omkarmakar** [comment]
image
Now i guess this works :)

**Pull request closed without merging**
