### PR TITLE
A blog section added 

### PR DESCRIPTION
**Pull request by CuriousHearted**

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@CuriousHearted All tests have to pass before I can merge your PR

**Comment by Amna-Hassan04** [comment]
@CuriousHearted and add the issue that u worked on

**Comment by zoobiasyed** [comment]
@CuriousHearted kindly add the necessary pictures or videos of what you have worked on, since it's not mentioned. Make sure to do it asap so that Amna can merge it. Also make sure it passes all the tests in order to get merged.

**Comment by zoobiasyed** [comment]
@CuriousHearted kindly add the necessary pictures and videos, make sure it passes all the tests.

**Comment by zoobiasyed** [comment]
@CuriousHearted your pr will only be merged if all the relevant details and pictures are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
No test cases are passing, no reply since 2 weeks so closing the pr

**Pull request closed without merging**
