### PR TITLE
Updated resource page with all the features

### PR DESCRIPTION
**Pull request by shivi13102**
All the feature added:
1. Mental Health Articles: A collection of articles and blog posts written by mental health professionals and wellness coaches.
2. Self-Care Tips: Advice on creating self-care routines, managing stress, and fostering positivity.
3. Guides & E-books: Downloadable content on topics like building resilience, practicing gratitude, or coping with stress.
4. Podcast/Audio Library: Short audio sessions on mental health topics like overcoming anxiety, building self-esteem, and more.
image
image
image

### CODE REVIEW

**Review by Amna-Hassan04 — COMMENTED** [review]
The resources page looks beautiful @shivi13102. I might give u a level3 for this work please do include a video that shows the working for the entire page so i can check and then merge this.

**Comment by Amna-Hassan04** [comment]
@shivi13102 please do mention the issue u solved too so i can link it.

**Comment by shivi13102** [comment]
By adding the resource page, I solved the following issues:
1. In-Depth Mental Health Information: Provides reliable articles and blogs for users seeking detailed mental health insights.
2. Guidance for Self-Care and Stress Management: Offers practical self-care tips to help users manage stress effectively.
3. Accessible Learning Resources: Supplies downloadable guides and e-books on topics like resilience and stress coping.
4. Convenient Access to Audio Resources: Includes podcasts and audio sessions for users who prefer listening to mental health content.
5. Supporting Diverse User Preferences: Offers various formats (articles, audio, e-books) to cater to different user needs.

**Comment by Amna-Hassan04** [comment]
@shivi13102 is the sidebar visible for the entire app or just this resources tab. it seems like the sidebar will show for the whole app, could u clarify this asap so i can merge your pr.

**Comment by shivi13102** [comment]
Only for the resource page

**Comment by shivi13102** [comment]
@Amna-Hassan04  could please merge my pull request once you get the moment?

**Pull request merged**
