### PR TITLE
Connected Database for feedback

### PR DESCRIPTION
**Pull request by ananyakaligal**
issue #12 
Connected Mongo db for feedback

Here's a video attached on how it works.

https://github.com/user-attachments/assets/793105d7-15a3-4246-aa81-937c49e11b16

### CODE REVIEW

**Comment by ananyakaligal** [comment]
Hey, I'm willing to connect all the inputs from the user to database, shall i create a new issue for that?

**Comment by suhaib-lone** [comment]
@ananyakaligal Hi! Your mongodb uri is exposed in the Client(). Add the MONGODB_URI instead as you have used the .env.

**Comment by Amna-Hassan04** [comment]
@ananyakaligal yes sure, make a discussion post for it first to decide what else also needs to be connected to the database.

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
dont you think in this their should be a option for name and email of user so that if we want to reach out to them we can.

**Pull request closed without merging**
