### PR TITLE
Documentation and license

### PR DESCRIPTION
**Pull request by priyanshaggarwal001**
it contains two files one is license file and second one is documentation file stating the use of the software and the features of the software
Screenshot 2024-10-03 at 9 33 35 AM
Screenshot 2024-10-03 at 9 33 59 AM

### CODE REVIEW

**Comment by priyanshaggarwal001** [comment]
solved issue#28

**Comment by Amna-Hassan04** [comment]
@priyanshaggarwal001 plz link the issue that this pr resolves so i can merge this

**Comment by priyanshaggarwal001** [comment]
solves issue number #28

**Review by Amna-Hassan04 — COMMENTED** [review]
added correct documentation for the project and license. looks good to be merged

**Pull request merged**
