### PR TITLE
Updated the feedback form

### PR DESCRIPTION
**Pull request by Satyamkumarjha4**
the feedback is improved as now user can give feedback based on what feature they like or dislike and this will be updated into the database which can be viewed by the owners and can help them improve their website

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@Satyamkumarjha4 which issue did you work on?

**Review by Amna-Hassan04 — COMMENTED** [review]
add the relevant video / screenshots so we know it works, and then i can merge it

**Comment by zoobiasyed** [comment]
@Satyamkumarjha4 kindly add the pictures or videos of what you have worked on so that we can go through all the necessary changes. Make sure all the tests are passed in order to get it merged.

**Comment by Amna-Hassan04** [comment]
No reply from almost 4 weeks so closing now

**Pull request closed without merging**
