### PR TITLE
Tip button position rectified

### PR DESCRIPTION
**Pull request by omkarmakar**
Problem number : #95 

New image:

image
I saw some changes are coming, implementation of mongodb for tips, as of now i have commented the the button integrated with the database, as it has no tips in it at this moment. Later on the buttons can be replace with no hassle.

Loved contributing to this unique problem, thank you so much for giving a chance @Amna-Hassan04 

please put the labels of gssoc extended and hacktoberfest :)

Thank you

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
@omkarmakar good work, could you plz add just a few tips in the data base so this doesnt look too empty like this, you can ask gpt to generate some tips that are like not too long and add them in the database, when your done with this let me know so i can merge your pr.

**Comment by omkarmakar** [comment]
I would request you to merge this PR instead, im getting a device specific error while dealing with pymongo database and I have some college assignments left, its reopening tomorrow, I hope you understand. Thank you :)

**Comment by Amna-Hassan04** [comment]
@omkarmakar I cant merge it like this, If your getting an error for adding anything to the database then how will I fix it, maybe just remove the database part and just make  a PR for the fixed tips location and also show a tip their before the button  just make  a array of 4 to 5 tips and loop around them for now for adding database I will open up a new issue if u wish to work on it you can ask to be assigned that

**Comment by omkarmakar** [comment]
@Amna-Hassan04 thats what its done, my PR has no issues with it, since my local machine was having problem with the MongoDB, i didnt make any further commits, so this PR has the tips from the defined list. It has nothing to do with the database. 

Thank you :)

**Comment by Amna-Hassan04** [comment]
@omkarmakar the entire purpose of this task was that when we click the button the tip show next to the gif, thats it if they dont show then nothing has been solved, dont connect the button to any database just make it show the tip retrieving from an array as it previously did, just in the correct location.

**Comment by zoobiasyed** [comment]
@omkarmakar your pr will only be merged if all the relevant details and pictures/videos are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
No reply from 2 weeks, so closing the pr

**Pull request closed without merging**
