### PR TITLE
enhance email verification using api

### PR DESCRIPTION
**Pull request by ayushdubey570**
enhanced the email verification process using api in python

### CODE REVIEW

**Comment by dev-shinde** [comment]
can you add view or image here

**Comment by zoobiasyed** [comment]
@ayushdubey570 kindly add the pictures or video of what you have worked on. Make sure it clears all the tests and the pr is updated in order to merge it properly.

**Comment by zoobiasyed** [comment]
@ayushdubey570 your pr will only be merged if all the relevant details and pictures are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
No Reply from 3 weeks test cases are not passing, closing the pr

**Pull request closed without merging**
