### PR TITLE
Personalized Anxiety Management

### PR DESCRIPTION
**Pull request by Sagar2006**
### Feature Addition: Personalized Anxiety Management

This PR implements the Personalized Anxiety Management feature in the SereniFi application. 

### Changes Made:
- Added a new section to allow users to input their mood, feelings, stress level, and any recent events contributing to their anxiety.
- Implemented AI-based responses using the Anthropic API to provide tailored recommendations.
- Updated documentation to include usage instructions and example inputs.

### Related Issue:
This feature is related to the issue #17 Feature Addition: Personalized Anxiety Management.

Thank you for your consideration!

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
which issue is this PR related too.

**Comment by Sagar2006** [comment]
Issue number 17

**Comment by Sagar2006** [comment]
Feature Addition: Personalized Anxiety Management

**Comment by Sagar2006** [comment]
I apologise to request PR without assigning the task. I raised an issue (#17 ) and then I requested PR. I am sorry for this mistake as I am a newbie in open source contributions. Kindly assign the task and then please consider this PR.

**Comment by Amna-Hassan04** [comment]
@Sagar2006 please make a post in discussions tab for this first , and attach all the screenshots etc

**Pull request closed without merging**
