### PR TITLE
Add Streamlit app for real-time IoT heart rate and stress monitoring

### PR DESCRIPTION
**Pull request by Shibika-Roy**
“Add Streamlit app for real-time IoT heart rate and stress monitoring
This dashboard enables real-time monitoring of heart rate and stress levels to personalize user relaxation experiences.

Simulated Data Monitoring:

Observe the heart rate and stress level metrics displayed in real time. These values update every second to simulate continuous data monitoring.
Confirm that both metrics (heart rate in BPM and stress level on a 1–10 scale) are displayed and updating smoothly.
User Experience:

The interface should provide a simple, easy-to-read layout with real-time updates on physiological data.
This simulation sets the stage for integrating actual IoT data for heart rate and stress monitoring.
This addition enables real-time physiological data monitoring, a feature that supports the app's mission to provide personalized and effective relaxation guidance. Future updates could replace simulated data with actual IoT device readings for further enhancement.

### CODE REVIEW

**Comment by Shibika-Roy** [comment]
please level as gssoc-extd hacktoberfest accepted

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 look into this, with only one day left, kindly assign this task too 1 or 2 contributors. The idea Shibika has provided will add more power to the app. If you think we have time than we should add this to the app.

**Comment by Amna-Hassan04** [comment]
@Shibika-Roy add all the necessary screenshots / video showcasing yoru work, also add the issue that you worked on

**Comment by Shibika-Roy** [comment]
https://github.com/user-attachments/assets/253bcea9-7557-4365-b4c3-c96f4a152508

**Comment by Shibika-Roy** [comment]
This issue you had been already assigned to me 2 weeks ago

**Comment by Shibika-Roy** [comment]
If this app comes with hardware devices in future it will work in this way

**Comment by Amna-Hassan04** [comment]
@Shibika-Roy plz add this as a tab in teh original app. plus with the heading you can add beta. add the relevant way any user can connect and check their heart rate and stress levels. plus mention the issue number you worked on.

**Comment by Shibika-Roy** [comment]
My issue is #77

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly review this.

**Comment by Shibika-Roy** [comment]
what would be the tab name??
 ...would it be like 'monitoring' tab

**Comment by Shibika-Roy** [comment]
I’ve added the Monitoring (Beta) tab to the Streamlit app, which provides real-time heart rate and stress level monitoring and includes connection instructions for IoT-enabled devices. This feature allows users to monitor their metrics directly in the SereniFi Guide app.

Conflict Status: I attempted to resolve conflicts between my branch and the main branch, but some conflicts remain that I couldn't fully resolve. If possible, could you assist with resolving the remaining conflicts to ensure this feature integrates smoothly?
Feature Details:

Tab: Monitoring (Beta)
Functionality: Real-time metrics with simulated data for heart rate and stress, along with connection instructions.
Instructions for Use: Users can follow setup instructions to connect their IoT devices and view their metrics in real time.

please inform me...

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly look into this, the conflicts are still not fully resolved.

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
first of all dont write your name in comment in the code, your profile will automatically show in the contributers column in the repository, While adding the tab you have changed the names of teh other tabs, u are also using a old version of the project which needs to be updated asap. now if u have added a new tab then plz make a video showcasing it and how it works overall with the app, also it would be better to show the process for connecting a monitoring device so I am sure to merge your pr. their are only 2 days left so for timely merge of your pr plz complete these steps asap so I can merge your pr.

**Comment by Shibika-Roy** [comment]
ok ok ...

**Comment by Shibika-Roy** [comment]
Uploading VID-20241108-WA0006.mp4…

**Comment by Shibika-Roy** [comment]
Uploading VID-20241108-WA0006.mp4

**Review by Shibika-Roy — COMMENTED** [review]
add-monitoring-tab branch.

**Comment by Shibika-Roy** [comment]
https://github.com/user-attachments/assets/6d70b91f-3cae-4dda-85d3-b109b5b0cc75

**Comment by zoobiasyed** [comment]
@Shibika-Roy did you complete all the tasks Amna told you to improve or change? If yes than provide with the relevant pictures.

**Comment by Shibika-Roy** [comment]
> @Shibika-Roy did you complete all the tasks Amna told you to improve or change? If yes than provide with the relevant pictures.

yes

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 kindly look into this.

**Review by Amna-Hassan04 — CHANGES_REQUESTED** [review]
Shibika I asked u to make a separate tab that shoudl show in the navbar, it really doenot look good how u have implemented this, i do not want you lose poinst by not getting your pr merged, for now just do this that add you montioring app functionality at the end of the calm space tab and remove this side bar. u still have almost 2 hours plz complete this asap so i can merge this.

**Comment by Shibika-Roy** [comment]
ok

**Comment by Amna-Hassan04** [comment]
@Shibika-Roy Good Luck, Im waiting for u fix this so u dont lose any points. the time is only till 7 pm today.

**Comment by Shibika-Roy** [comment]
okk I understand @Amna-Hassan04

**Comment by Amna-Hassan04** [comment]
@Shibika-Roy and be sure to use the latest version of the project

**Comment by Amna-Hassan04** [comment]
@Shibika-Roy also add a screenshot of how it looks

**Pull request merged**
