### PR TITLE
Update app.py

### PR DESCRIPTION
**Pull request by jiyasantani**
email validation   
github email valid

### CODE REVIEW

**Comment by dev-shinde** [comment]
@jiyasantani can you upload an after screenshot of the email validation; or screen-record

**Comment by jiyasantani** [comment]
> @jiyasantani can you upload an after screenshot of the email validation; or screen-record

**Comment by jiyasantani** [comment]
> @jiyasantani can you upload an after screenshot of the email validation; or screen-record

uploaded screenshot

**Review by Amna-Hassan04 — APPROVED** [review]
looks good to be merged.

**Comment by Amna-Hassan04** [comment]
@jiyasantani were you assigned this issue? I think I assigned this task to someone else.

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 this branch is facing some conflicts, kindly look into it.

**Comment by zoobiasyed** [comment]
@jiyasantani your pr will only be merged if all the relevant details and pictures/videos are mentioned. Also all the test cases should be passed, before the deadline.

**Comment by Amna-Hassan04** [comment]
issue not assigned to this contributer goes against gssoc guidelines to merge this.

**Pull request closed without merging**
