### PR TITLE
Feature #107 And Added Bottom Footer

### PR DESCRIPTION
**Pull request by sarinsanyal**
On the basis of #107, I added the Bottom Footer and the **Social Icons (with only GitHub and LinkedIn Working)**. 

Also added a **Newsletter Subscribing** implementation and **"Terms and Conditions", "Privacy Policy",** etc. links that don't redirect  to anywhere as of now.

At the end, I put in **Acknowledgements for the creators and the Contributors.**

https://github.com/user-attachments/assets/441299f4-eabd-474d-b712-d445877e5ca5

@Amna-Hassan04 Please take a look at this video, and let me know if everything is alright. Thank you!

### CODE REVIEW

**Comment by sarinsanyal** [comment]
@Amna-Hassan04 If you think this is alright, can you please merge the commit? Thank you once again.

**Review by sarinsanyal — COMMENTED** [review]
Removed the Newsletter UI and the Script Code, according to the changes prescribed. Based on #107 and https://github.com/Amna-Hassan04/Serenity-Guide/discussions/108#discussioncomment-10929856

@Amna-Hassan04 Please let me know if it is alright now. Also please add the GSSoC and Hacktoberfest Labels. Thank you!

**Comment by Amna-Hassan04** [comment]
@sarinsanyal plz do make sure your pr uses the latest version of the project so i can merge

**Comment by sarinsanyal** [comment]
I have resolved the conflict @Amna-Hassan04. Please check and let me know if it's alright.

**Comment by Amna-Hassan04** [comment]
@sarinsanyal plz confirm that this PR is using the latest version of the project so i can merge.

**Comment by zoobiasyed** [comment]
@sarinsanyal kindly update your pr to the latest version so that Amna can merge it. As the test already mentions that it has failed in having the pr up to date. Kindly do it asap.

**Comment by sarinsanyal** [comment]
@Amna-Hassan04 @zoobiasyed I have merged it once again. Please let me know if I can help you in any other way. Thank you.

**Comment by zoobiasyed** [comment]
@Amna-Hassan04 I think it's good to go now. Thank you @sarinsanyal.

**Comment by Amna-Hassan04** [comment]
@sarinsanyal sorry for the delay can you plz update it to the latest project once again. It is behind by 7 commits

**Pull request merged**
