### PR TITLE
Navbar enhanced

### PR DESCRIPTION
**Pull request by Saaarthak0102**
# Enhanced the navbar with better design!
## Fixes Issue #148 
image

### CODE REVIEW

**Comment by Saaarthak0102** [comment]
please review and merge! @Amna-Hassan04

**Review by Saaarthak0102 — COMMENTED** [review]
reviewed

**Comment by Saaarthak0102** [comment]
please merge @Amna-Hassan04

**Comment by Amna-Hassan04** [comment]
@Saaarthak0102 the color looks really dull for the navbar can u try giving the same color that we already had.

**Comment by Amna-Hassan04** [comment]
@Saaarthak0102 and their have been recent pushes to teh main that have another tab in the navbar i think  plz update your pr to use the latest version of the project.

**Comment by Saaarthak0102** [comment]
Creating a new PR

**Pull request closed without merging**
