### PR TITLE
#Add Greetings Bot

### LINKED ISSUE #14: Add Greeting Bot
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested!

### PR DESCRIPTION
**Pull request by KiranBaliga**
closes #14 

This is a PR that addresses the addition of a simple bot that displays the message as a comment on a newly raised PR or issue submited by new users. Thank you. Please add gssoc24-ext and level1 label to the PR. Thanks again.

### CODE REVIEW

**Comment by Amna-Hassan04** [comment]
please read the instructions I gave you and resubmit this. this does not have the text I asked you to add.

**Comment by KiranBaliga** [comment]
@Amna-Hassan04 May I know where can I find those instructions?

**Comment by Amna-Hassan04** [comment]
In the issue thread.

**Comment by KiranBaliga** [comment]
@Amna-Hassan04 I have used a testing account to push a commit using a forked repo and the Github action workflow passed with the message as expected. Link to show the bot works on a forked repo : https://github.com/KiranBaliga/Serenity-Guide/pull/1

**Pull request merged**
