### PR TITLE
Added "Simon Game Challenge" under Mood-Boosting Games

### PR DESCRIPTION
**Pull request by sanyadureja**
- Embedding the game using i-frame is facing some issues due to Streamlit's limitations thus I've come with this approach.

- I've made a new function for simon_game_challenge() and added a new button "Simon Game Challenge" below Start Mini Games under Mood-Boosting Games.

- The Simon Game Challenge opens a table with the game's description, instructions and button to play.

Please have a look at the video, give your meaningful suggestions. 

https://github.com/user-attachments/assets/d3970d03-12d0-411a-b495-da28980bc197

### CODE REVIEW

**Comment by sanyadureja** [comment]
@Amna-Hassan04 Now, I've raised my PR #172 and resolves the issue #80 , looking forward to getting it merged, please add all the necessary labels(GSSOC-EXT, Hacktoberfest and the level).

**Comment by sanyadureja** [comment]
> @Amna-Hassan04 Now, I've raised my PR #172 and resolves the issue #80 , looking forward to getting it merged, please add all the necessary labels(GSSOC-EXT, Hacktoberfest and the level).

@Amna-Hassan04 any update on this?

@sanjay-kv please look into this, if possible try connecting with her. Only few days are left now. Thank you

**Comment by sanyadureja** [comment]
@Amna-Hassan04 I've raised my PR #172 and resolved the issue #80.

Please merge my PR. Looking forward to your response.

**Comment by sanjay-kv** [comment]
@sanyadureja I cant merge on some one else repo, you need tag admin or mentors.

**Comment by sanyadureja** [comment]
> @sanyadureja I cant merge on some one else repo, you need tag admin or mentors.

I've tagged @Amna-Hassan04 and am waiting for her response.

**Comment by Amna-Hassan04** [comment]
@sanyadureja isnt this game the same one that had some bugs, have you solved the bugs? plz link it so i can test it.

**Comment by sanyadureja** [comment]
> * Embedding the game using i-frame is facing some issues due to Streamlit's limitations thus I've come with this approach.
> * I've made a new function for simon_game_challenge() and added a new button "Simon Game Challenge" below Start Mini Games under Mood-Boosting Games.
> * The Simon Game Challenge opens a table with the game's description, instructions and button to play.
> 
> Please have a look at the video, give your meaningful suggestions.
> 
>  simon_game.mp4

Check the video here

**Comment by Amna-Hassan04** [comment]
@sanyadureja I dont know why every time i try to do like the second level or the second step it always fails even when I do it right, i might be doing it wrong so maybe make a video of the gameplay in action bcz its not working well for me. plz take a look at it. The above video that you  have attached is fine. I want to confirm that the gameplay actually works.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 Check the game play video, it's working fine.


https://github.com/user-attachments/assets/d050d714-0e31-4c93-8f1a-8e2507c56f9d

Is my PR ready to merge now?

**Comment by Amna-Hassan04** [comment]
@sanyadureja yes i guess this is ready to be merged plz make sure you update the pr to use the latest version of the project so i can merge.

**Comment by Amna-Hassan04** [comment]
@sanyadureja just a recommendation here that in the game page maybe write a simple instructions or two for new users bcz it is confusing that we have to do the previous pattern and the new one too. even as a game dev my self I struggled to play it bcz their were no instructions.  you can implement this later though I will merge your pr when you can confirm your using the latest version of the project.

**Review by Amna-Hassan04 — APPROVED** [review]
seems to work, the linked game does need polishing though such as atleast instructions as to how to play the game.

**Comment by sanyadureja** [comment]
> @sanyadureja yes i guess this is ready to be merged plz make sure you update the pr to use the latest version of the project so i can merge.

Latest version is already there, I didn't do any changes

**Comment by sanyadureja** [comment]
> @sanyadureja just a recommendation here that in the game page maybe write a simple instructions or two for new users bcz it is confusing that we have to do the previous pattern and the new one too. even as a game dev my self I struggled to play it bcz their were no instructions. you can implement this later though I will merge your pr when you can confirm your using the latest version of the project.

Alright I will implement it later for sure, thanks for the suggestions.

**Comment by sanyadureja** [comment]
@Amna-Hassan04 I think atleast level 2 should be assigned, level 1 is really a small change.

**Pull request merged**
